import { useNavigate } from "@tanstack/react-router";
import { Bot, Clipboard, Plus, ShieldCheck } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { toast } from "sonner";
import { Conversation, ConversationContent, ConversationEmptyState, ConversationScrollButton } from "@/components/ai-elements/conversation";
import { Message, MessageAction, MessageActions, MessageContent, MessageResponse } from "@/components/ai-elements/message";
import { PromptInput, PromptInputFooter, PromptInputSubmit, PromptInputTextarea } from "@/components/ai-elements/prompt-input";
import { Shimmer } from "@/components/ai-elements/shimmer";
import { Button } from "@/components/ui/button";
import { createThread, newId, readThreads, upsertThread, type ChatThread, type LocalMessage } from "@/lib/chat-storage";
import { generateChatReply } from "@/lib/workplace";

const prompts = ["Plan a focused team meeting", "Help me prioritise this week", "Prepare constructive feedback", "Draft a project update"];
export function ChatPage({ threadId }: { threadId: string }) {
  const navigate = useNavigate(); const textareaRef = useRef<HTMLTextAreaElement>(null); const [thread, setThread] = useState<ChatThread | null>(null); const [loading, setLoading] = useState(false);
  useEffect(() => { const found = readThreads().find((item) => item.id === threadId); if (found) setThread(found); else { const created = { ...createThread(), id: threadId }; upsertThread(created); setThread(created); } }, [threadId]);
  useEffect(() => { textareaRef.current?.focus(); }, [threadId, loading]);
  const submit = (text: string) => { if (!thread || !text.trim() || loading) return; const user: LocalMessage = { id: newId(), role: "user", text: text.trim(), createdAt: new Date().toISOString() }; const optimistic = { ...thread, title: thread.messages.length ? thread.title : text.trim().slice(0, 42), updatedAt: new Date().toISOString(), messages: [...thread.messages, user] }; setThread(optimistic); upsertThread(optimistic); setLoading(true); window.setTimeout(() => { const assistant: LocalMessage = { id: newId(), role: "assistant", text: generateChatReply(text), createdAt: new Date().toISOString() }; const completed = { ...optimistic, updatedAt: new Date().toISOString(), messages: [...optimistic.messages, assistant] }; setThread(completed); upsertThread(completed); setLoading(false); }, 800); };
  const newChat = () => { const created = createThread(); upsertThread(created); void navigate({ to: "/chat/$threadId", params: { threadId: created.id } }); };
  if (!thread) return <div className="grid h-[calc(100svh-4rem)] place-items-center"><Shimmer>Loading conversation…</Shimmer></div>;
  return <div className="flex h-[calc(100svh-4rem)] flex-col"><div className="flex items-center justify-between border-b bg-card px-4 py-3 md:px-8"><div className="min-w-0"><h1 className="truncate text-base font-semibold">{thread.title}</h1><p className="text-xs text-muted-foreground">Private to this browser</p></div><Button size="sm" variant="outline" onClick={newChat}><Plus />New chat</Button></div><Conversation className="mx-auto w-full max-w-4xl"><ConversationContent className="min-h-full px-4 py-8 md:px-8">{thread.messages.length === 0 ? <ConversationEmptyState icon={<div className="grid size-14 place-items-center rounded-lg bg-brand-deep text-primary-foreground"><Bot className="size-7" /></div>}><div className="max-w-xl"><h2 className="text-2xl font-semibold">How can I help with your work?</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">Ask for planning, writing, feedback, meeting preparation, or practical next steps.</p><div className="mt-6 grid gap-2 sm:grid-cols-2">{prompts.map((prompt) => <Button key={prompt} variant="outline" className="h-auto justify-start whitespace-normal py-3 text-left" onClick={() => submit(prompt)}>{prompt}</Button>)}</div></div></ConversationEmptyState> : thread.messages.map((message) => <Message key={message.id} from={message.role}><MessageContent className={message.role === "user" ? "bg-primary text-primary-foreground" : undefined}><MessageResponse>{message.text}</MessageResponse></MessageContent>{message.role === "assistant" && <MessageActions><MessageAction tooltip="Copy response" onClick={() => { void navigator.clipboard.writeText(message.text); toast.success("Response copied"); }}><Clipboard /></MessageAction></MessageActions>}</Message>)}{loading && <Message from="assistant"><MessageContent><Shimmer>Thinking through your request…</Shimmer></MessageContent></Message>}</ConversationContent><ConversationScrollButton /></Conversation><div className="border-t bg-background px-4 py-4"><div className="mx-auto max-w-4xl"><PromptInput onSubmit={(message) => submit(message.text)} className="rounded-lg border bg-card shadow-sm"><PromptInputTextarea ref={textareaRef} placeholder="Ask a workplace question or describe a task…" disabled={loading} className="min-h-20" /><PromptInputFooter className="justify-between"><span className="flex items-center gap-1 text-xs text-muted-foreground"><ShieldCheck className="size-3.5" />Review before use</span><PromptInputSubmit status={loading ? "submitted" : "ready"} disabled={loading} /></PromptInputFooter></PromptInput></div></div></div>;
}
