import { useState } from "react";
import { Check, Clipboard, Mail, RefreshCw, Wand2 } from "lucide-react";
import { toast } from "sonner";
import { PageFrame, ResponsibleNotice } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { generateEmail, type EmailTone } from "@/lib/workplace";

export function EmailPage() {
  const [recipient, setRecipient] = useState(""); const [purpose, setPurpose] = useState(""); const [tone, setTone] = useState<EmailTone>("Formal"); const [output, setOutput] = useState(""); const [loading, setLoading] = useState(false); const [version, setVersion] = useState(0); const [copied, setCopied] = useState(false);
  const generate = () => { if (!purpose.trim()) { toast.error("Add an email purpose first."); return; } setLoading(true); window.setTimeout(() => { setOutput(generateEmail(recipient, purpose, tone, version)); setVersion((value) => value + 1); setLoading(false); }, 650); };
  const copy = async () => { await navigator.clipboard.writeText(output); setCopied(true); toast.success("Email copied"); window.setTimeout(() => setCopied(false), 1400); };
  return <PageFrame eyebrow="Communication" title="Smart Email Generator" description="Create a polished workplace email with the right structure and tone."><div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><Card className="rounded-lg shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Mail className="size-5 text-primary" />Email brief</CardTitle></CardHeader><CardContent className="space-y-5"><div className="space-y-2"><Label htmlFor="recipient">Recipient or context</Label><Input id="recipient" value={recipient} onChange={(event) => setRecipient(event.target.value)} placeholder="e.g. Project stakeholders" /></div><div className="space-y-2"><Label htmlFor="purpose">Purpose</Label><Textarea id="purpose" value={purpose} onChange={(event) => setPurpose(event.target.value)} className="min-h-36" placeholder="e.g. Ask for approval on the revised launch plan by Friday" /></div><fieldset><legend className="mb-2 text-sm font-medium">Tone</legend><div className="grid grid-cols-3 gap-2">{(["Formal", "Friendly", "Persuasive"] as EmailTone[]).map((item) => <Button key={item} type="button" variant={tone === item ? "default" : "outline"} onClick={() => setTone(item)}>{item}</Button>)}</div></fieldset><Button className="w-full" onClick={generate} disabled={loading}><Wand2 />{loading ? "Drafting email…" : "Generate email"}</Button></CardContent></Card><Card className="rounded-lg shadow-sm"><CardHeader className="flex-row items-center justify-between space-y-0"><CardTitle className="text-lg">Editable draft</CardTitle>{output && <div className="flex gap-2"><Button size="sm" variant="outline" onClick={generate} disabled={loading}><RefreshCw />Regenerate</Button><Button size="sm" onClick={copy}>{copied ? <Check /> : <Clipboard />}{copied ? "Copied" : "Copy"}</Button></div>}</CardHeader><CardContent>{loading ? <div className="grid min-h-96 place-items-center rounded-lg border border-dashed bg-muted/40"><div className="text-center"><RefreshCw className="mx-auto mb-3 size-6 animate-spin text-primary" /><p className="text-sm font-medium">Shaping your message…</p></div></div> : output ? <Textarea aria-label="Generated email" value={output} onChange={(event) => setOutput(event.target.value)} className="min-h-96 resize-y bg-background leading-7" /> : <div className="grid min-h-96 place-items-center rounded-lg border border-dashed bg-muted/30 p-8 text-center"><div><div className="mx-auto mb-4 grid size-12 place-items-center rounded-lg bg-brand-soft text-primary"><Mail /></div><p className="font-medium">Your email will appear here</p><p className="mt-2 max-w-xs text-sm text-muted-foreground">Add the purpose and context, choose a tone, then generate an editable draft.</p></div></div>}</CardContent></Card></div><div className="mt-6"><ResponsibleNotice /></div></PageFrame>;
}
