import { useState } from "react";
import { Check, Clipboard, FileSearch, RefreshCw, Wand2 } from "lucide-react";
import { toast } from "sonner";
import { PageFrame, ResponsibleNotice } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { generateResearch } from "@/lib/workplace";

export function ResearchPage() {
 const [input, setInput] = useState(""); const [output, setOutput] = useState(""); const [loading, setLoading] = useState(false); const [copied, setCopied] = useState(false);
 const generate = () => { if (input.trim().length < 8) { toast.error("Add a topic or a little more source text."); return; } setLoading(true); window.setTimeout(() => { setOutput(generateResearch(input)); setLoading(false); }, 750); };
 const copy = async () => { await navigator.clipboard.writeText(output); setCopied(true); toast.success("Research notes copied"); window.setTimeout(() => setCopied(false), 1400); };
 return <PageFrame eyebrow="Analysis" title="AI Research Assistant" description="Distil a topic or source article into concise findings and practical next steps."><div className="grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><Card className="rounded-lg shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><FileSearch className="size-5 text-primary" />Research input</CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label htmlFor="research-input">Topic or pasted article</Label><Textarea id="research-input" value={input} onChange={(event) => setInput(event.target.value)} className="min-h-80" placeholder="Describe a workplace topic or paste article text here…" /><p className="text-xs text-muted-foreground">The assistant identifies recurring terms and adapts the analysis to your input.</p></div><Button className="w-full" onClick={generate} disabled={loading}><Wand2 />{loading ? "Analysing…" : "Generate research brief"}</Button></CardContent></Card><Card className="rounded-lg shadow-sm"><CardHeader className="flex-row items-center justify-between space-y-0"><CardTitle className="text-lg">Editable research brief</CardTitle>{output && <Button size="sm" onClick={copy}>{copied ? <Check /> : <Clipboard />}{copied ? "Copied" : "Copy"}</Button>}</CardHeader><CardContent>{loading ? <div className="grid min-h-96 place-items-center rounded-lg border border-dashed bg-muted/40"><div className="text-center"><RefreshCw className="mx-auto mb-3 size-6 animate-spin text-primary" /><p className="text-sm font-medium">Structuring the key findings…</p></div></div> : output ? <Textarea aria-label="Generated research brief" value={output} onChange={(event) => setOutput(event.target.value)} className="min-h-[31rem] resize-y bg-background leading-7" /> : <div className="grid min-h-[31rem] place-items-center rounded-lg border border-dashed bg-muted/30 p-8 text-center"><div><div className="mx-auto mb-4 grid size-12 place-items-center rounded-lg bg-brand-soft text-primary"><FileSearch /></div><p className="font-medium">A structured brief will appear here</p><p className="mt-2 max-w-xs text-sm text-muted-foreground">You’ll receive a summary, insights, important points, recommendations, and verification questions.</p></div></div>}</CardContent></Card></div><div className="mt-6"><ResponsibleNotice /></div></PageFrame>;
}
