import { useEffect, useState } from "react";
import { Database, RotateCcw, Settings2, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { PageFrame, ResponsibleNotice } from "@/components/app-shell";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { CHAT_STORAGE_KEY, CHAT_EVENT } from "@/lib/chat-storage";
const SETTINGS_KEY = "workmate-settings-v1";
export function SettingsPage() { const [detail, setDetail] = useState("balanced"); const [concise, setConcise] = useState(true); useEffect(() => { try { const saved = JSON.parse(localStorage.getItem(SETTINGS_KEY) ?? "{}"); if (saved.detail) setDetail(saved.detail); if (typeof saved.concise === "boolean") setConcise(saved.concise); } catch {} }, []); useEffect(() => { localStorage.setItem(SETTINGS_KEY, JSON.stringify({ detail, concise })); }, [detail, concise]); const clear = () => { localStorage.removeItem(CHAT_STORAGE_KEY); window.dispatchEvent(new Event(CHAT_EVENT)); toast.success("Local chat history cleared"); }; return <PageFrame eyebrow="Preferences" title="Settings" description="Control your local experience. These preferences stay in this browser."><div className="grid gap-6 lg:grid-cols-2"><Card className="rounded-lg shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Settings2 className="size-5 text-primary" />Writing preferences</CardTitle></CardHeader><CardContent className="space-y-6"><div className="space-y-2"><Label htmlFor="detail">Default response detail</Label><Select value={detail} onValueChange={setDetail}><SelectTrigger id="detail"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="concise">Concise</SelectItem><SelectItem value="balanced">Balanced</SelectItem><SelectItem value="detailed">Detailed</SelectItem></SelectContent></Select></div><div className="flex items-center justify-between gap-4 rounded-lg border p-4"><div><Label htmlFor="direct-style">Direct writing style</Label><p className="mt-1 text-xs text-muted-foreground">Prefer short sentences and explicit next steps.</p></div><Switch id="direct-style" checked={concise} onCheckedChange={setConcise} /></div></CardContent></Card><Card className="rounded-lg shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Database className="size-5 text-primary" />Local data</CardTitle></CardHeader><CardContent><div className="flex items-start gap-3 rounded-lg bg-brand-soft p-4"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-primary" /><p className="text-sm leading-6">Conversations and preferences are saved only in this browser. They do not sync across devices.</p></div><Button variant="outline" className="mt-5" onClick={clear}><RotateCcw />Clear chat history</Button></CardContent></Card></div><div className="mt-6"><ResponsibleNotice /></div></PageFrame>; }
